weights: ''
cfg: cfg/training/yolov7-tiny.yaml
data: data/fms.yaml
hyp: data/hyp.scratch.tiny.yaml
epochs: 300
batch_size: 64
img_size:
- 320
- 320
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: 2,3
multi_scale: false
single_cls: false
adam: false
sync_bn: true
local_rank: 0
workers: 8
project: runs/train
entity: null
name: yolov7-fms-mix
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 0
world_size: 2
global_rank: 0
save_dir: runs/train/yolov7-fms-mix4
total_batch_size: 128
